apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT1RZME1qVTBORGd3SGhjTk1qTXhNREEwTVRNeE56STRXaGNOTXpNeE1EQXhNVE14TnpJNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT1RZME1qVTBORGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRQ1NsSlVUVzMwRW1LNjN6Q0RlbkRpVzBSRVRNWHVwNllIMnMxc1VGMjYKb3FtK3I0cjhNWVJMSkhyajFiMEpQa3MyMFQxRmQ4ODlVV2YvREJEOGtoYW5vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVQ4QzFBRFB6MytOb1dWNHhVaitECk5Dd3JpVTh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUs5b2FvWE9vSzBCbW5lWXZSaE4xbUpvdlpicG5nSUkKVGZzbFNrZEZSekU1QWlBVVV6THB6amFadnl1Y1dvTFBMdSt1UDhtTW11OU5KL3JZMjJoNitFdkJydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.80.10:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: 
    client-key-data: 
